### ISSUE TITLE
I forgot to download ca.pem where do I get it now?

### ISSUE THREAD

**Issue by maiatoday** [OfferZen-Make/iot_robots-activity-pubsub_with_javascript#2]
:crying_cat_face:

**Comment by jeriko** [comment]
Here we go! Just rename it to `ca.pem`, GitHub doesn't let me upload `.pem` files.

 [ca.txt](https://github.com/OfferZen-Make/iot_robots-activity-pubsub_with_javascript/files/2066182/ca.txt)

Will close this ticket once we've added dashboard instructions to the "create a thing" readme.

**Comment by nuclearnic** [comment]
@jeriko we can close this now right ? https://github.com/OfferZen-Make/iot_robots-activity-create_aws_thing
